language: cpp
os: linux
compiler: gcc

cache: # see https://docs.travis-ci.com/user/caching/
- directories:
  - $HOME/.cache

addons:
  apt:
    packages: 
      - lcov
      - doxygen

install:
# (fake) install dependencies (usually involves wget, configure, make, ...)
# install into cache folder (build binaries+headers only, no sources and do NOT build there)
- mkdir -p $HOME/.cache
- touch $HOME/.cache/mydependency.so

script: ./build.sh

after_success:
# Create lcov report
# capture coverage info
- lcov --directory . --capture --output-file coverage.info
# filter out system and extra files.
- lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' '*/tests/*' '*/third_party/*' --output-file coverage.info
# output coverage data for debugging
- lcov --list coverage.info
# Uploading to CodeCov
# '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
- bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage reports"

# https://github.com/EmaroLab/docs/wiki/Automatic-deployment-Doxygen-documentation
# Generate and deploy documentation
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/doc/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master


notifications:
  email:
    - frns.roy@gmail.com